### ISSUE TITLE
stop previous animation when animateProgressFill() is called while an animation is happening

### ISSUE THREAD

**Issue by tom91136** [FilipPudak/ProgressPieView#5]
When I call `animateProgressFill(n)` and then call `animateProgressFill(n+10)` (where n = {0> n > max-10}) before the the first animation completes, this is thrown:

  //The numbers are made up
    java.lang.IllegalArgumentException: Animation progress (16) is lower than the current progress (17)
            at com.filippudak.ProgressPieView.ProgressPieView$AnimationRunnable.run(ProgressPieView.java:555)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)

`animateProgressFill()` and `animateProgressFill(int)` should check for running runnables and stop them first, then start the current animation

Also, is there any reasons why animating decrements are are not allowed?

**Comment by FilipPudak** [comment]
Hi,
Animation of decrements was not foreseen by Pavlos when he added it I guess. I can take a look.

**Comment by FilipPudak** [comment]
Added patch with requested functionalities in 97c35acf59accb00109f0458b65982eec9b6c8a3. New version should be in Maven in a few hours.
